[IMP] sign_oca: Allow to store geolocalization
OCA/sign pull request #16
Opened 2024-01-19 21:38 UTC by etobella

Using geolocalization can be useful in order to prove the authorship of the signature

2024-08-25 19:55 UTC, marcelsavegnago commented
@etobella can you rebase please ?

2024-08-27 15:36 UTC, marcelsavegnago commented
@WesleyOliveira98, could you please review?

2024-08-30 19:20 UTC, WesleyOliveira98 reviewed
[FUNCTIONAL REVIEW]

Create a Sign Oca Template with Ask Location enabled
![image](https://github.com/user-attachments/assets/dc1edd52-23a7-4459-8304-e9f10e001387)

Testing on Runboat (which uses HTTP), the browser blocks geolocation retrieval. This is a standard security restriction for pages not served over HTTPS. As a result, it consistently returns an error.

```
TypeError: Cannot read properties of undefined (reading 'latitude')
    at SignOcaPdfPortal._onClickSign (http://oca-sign-16-0-pr16-b490badf47d5.runboat.odoo-community.org/web/assets/212-b5b3804/web.assets_frontend.min.js:9355:80)
```

To work around this, I had to run Chrome with the following command (using Ubuntu):

```
google-chrome --unsafely-treat-insecure-origin-as-secure="http://oca-sign-16-0-pr16-b490badf47d5.runboat.odoo-community.org/" --user-data-dir=/tmp/chrome_dev_test
```

This allowed me to enable location access for Runboat and proceed with the signing process. It worked perfectly, and the system correctly retrieved my latitude and longitude.
![image](https://github.com/user-attachments/assets/6703e1a4-791d-49a7-a626-de13f6616759)

And then, i reopened Chrome with the flags and blocked the site from accessing the geolocation, which resulted in the same error as before.

2024-08-30 19:32 UTC, WesleyOliveira98 requested changes

2024-08-30 19:32 UTC, WesleyOliveira98 commented on sign_oca/static/src/components/sign_oca_pdf/sign_oca_pdf.esm.js
> +            },
I think you should prevent the error in the code by handling the possibility of geolocation not being available. For example:

```
latitude: position ? position.coords.latitude : false,
longitude: position ? position.coords.longitude : false,
```

2024-08-30 19:32 UTC, WesleyOliveira98 commented on sign_oca/static/src/components/sign_oca_pdf_portal/sign_oca_pdf_portal.esm.js
> +                },
I think you should prevent the error in here as well

2024-08-30 19:32 UTC, WesleyOliveira98 commented on sign_oca/models/sign_oca_request.py
> +    def action_sign(self, items, access_token=False, latitude=False, longitude=False):
Additionally, in the `actions_sign` method, you could add a ValidationError if the template is marked as `ask_location` and the latitude and longitude are not provided.

2024-10-17 09:38 UTC, etobella commented on sign_oca/models/sign_oca_request.py
> +    def action_sign(self, items, access_token=False, latitude=False, longitude=False):
I don't think so. We cannot make it required as the user can deny the information.

2024-10-17 09:41 UTC, etobella commented on sign_oca/static/src/components/sign_oca_pdf/sign_oca_pdf.esm.js
> +            },
Sure!

2024-10-17 09:41 UTC, etobella commented on sign_oca/static/src/components/sign_oca_pdf_portal/sign_oca_pdf_portal.esm.js
> +                },
Sure!

2024-10-17 09:42 UTC, etobella commented
@WesleyOliveira98 Comments attended

2024-10-17 13:01 UTC, WesleyOliveira98 approved these changes
LGTM

2024-10-17 14:03 UTC, marcelsavegnago approved these changes
LGTM

2024-10-17 14:05 UTC, pedrobaeza commented on sign_oca/static/src/components/sign_oca_pdf/sign_oca_pdf.esm.js
> +                    console.error("User denied the request for geolocation.");
I don't think this should be issued on the console, don't you think?

2024-10-25 18:09 UTC, etobella commented on sign_oca/static/src/components/sign_oca_pdf/sign_oca_pdf.esm.js
> +                    console.error("User denied the request for geolocation.");
Sure. I will leave it as debug :wink:

2024-10-31 09:16 UTC, etobella commented
/ocabot merge major

2024-10-31 09:21 UTC, merged