[14.0][FIX] sign_oca: Some fixes
OCA/sign pull request #18
Opened 2024-02-27 14:33 UTC by PauBForgeFlow

1. Add _Sign_ button in request form (it was only in tree view).
2. Fix configure template action when it is created from a request.

2024-02-27 14:41 UTC, BernatPForgeFlow approved these changes

2024-02-27 15:04 UTC, etobella requested changes

2024-02-27 15:04 UTC, etobella commented on sign_oca/models/sign_oca_request.py
> +                record.signatory_data and int(max(record.signatory_data.keys())) or 0
Reviewing this is probably a bad decision, we should need to do:
`max([int(key) for key in record.signatory_data.keys()])`

For example, if you do max(['9', '10']) the result is '9'

2024-02-27 15:04 UTC, etobella commented on sign_oca/models/sign_oca_request.py
> +        self._set_action_log("view")
Why do you change this?

2024-02-27 15:10 UTC, PauBForgeFlow commented on sign_oca/models/sign_oca_request.py
> +        self._set_action_log("view")
There is not an action named "configure". Another change could be to create it.

2024-02-28 09:03 UTC, victoralmau commented on sign_oca/models/sign_oca_request.py
> +        self._set_action_log("view")
IMO the correction should be https://github.com/OCA/sign/pull/8/commits/e0591479ae850c5b7b02cb7d563fb5f49d2ff2c3

2024-02-28 09:11 UTC, etobella commented on sign_oca/models/sign_oca_request.py
> +        self._set_action_log("view")
I do agree with @victoralmau

2024-02-28 10:36 UTC, PauBForgeFlow commented on sign_oca/models/sign_oca_request.py
> +        self._set_action_log("view")
Deleted. This will be fixed with @victoralmau commit.

2024-03-04 08:49 UTC, pedrobaeza commented
Can you rebase?

2024-03-05 18:04 UTC, pedrobaeza approved these changes
/ocabot merge minor

2024-03-05 18:05 UTC, pedrobaeza commented
@etobella I have launched the merge command as your requests were attended.

2024-03-05 18:07 UTC, merged