[ADD] Addon: sale_order_sign_oca
OCA/sign pull request #64
Opened 2024-09-20 17:38 UTC by Tiago370

Sign module for the sale order.

2024-09-22 19:41 UTC, mileo commented
@Tiago370 could fix the readme files?

2024-09-24 12:50 UTC, mileo approved these changes

2024-09-25 15:38 UTC, victoralmau requested changes
Code and functional review OK

2024-09-25 15:38 UTC, victoralmau commented on sale_order_sign_oca/views/sign_oca_request.xml
> +        <field name="inherit_id" ref="sign_oca.sign_oca_request_search_view" />
```suggestion
        <field name="inherit_id" ref="sign_oca.sign_oca_request_search_view" />
        <field
            name="groups_id"
            eval="[(6, 0, [ref('sales_team.group_sale_salesman')])]"
        />

```

2024-09-25 15:38 UTC, victoralmau commented on sale_order_sign_oca/models/sale_order.py
> +        return res
Although the flow is correct, I am not sure that this is “_necessary_” or that you always want to do this (create and send a signature request when creating a quote, perhaps when sending it by email). 

One possibility would be to add to res.config.settings the ability to select the order states in which you want to auto-create.

2024-10-05 18:42 UTC, Tiago370 commented
@victoralmau It is now possible to select in which state of the sales order the subscription request will be automatically generated, as you suggested.

@mileo

2024-10-07 06:27 UTC, victoralmau requested changes
Code review OK

2024-10-07 06:27 UTC, victoralmau commented on sale_order_sign_oca/views/res_config_settings.xml
> +</div> -->
```suggestion
```

2024-10-07 06:27 UTC, victoralmau commented on sale_order_sign_oca/views/res_config_settings.xml
> +                        title="The mode selected here applies as invoicing policy of any new product created but not of products already existing."
```suggestion
                        id="div_sale_order_sign_oca_state"
```

2024-10-07 12:36 UTC, Tiago370 commented
@victoralmau everything fixed.

2024-10-07 13:31 UTC, victoralmau approved these changes
Code review OK

2024-10-07 13:55 UTC, rvalyi approved these changes

2024-10-07 14:56 UTC, pedrobaeza commented
/ocabot merge nobump

2024-10-07 15:00 UTC, merged